# Generated by Django 3.0.1 on 2019-12-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW_app', '0002_auto_20191227_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(default='images/mypic.png', upload_to='WW_app/images/'),
        ),
    ]
