# Generated by Django 3.0.1 on 2019-12-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW_app', '0003_auto_20191227_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post_job_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post_project_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='post_job',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='post_project',
            name='freelancer_id',
        ),
        migrations.RemoveField(
            model_name='post_project',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='views',
            name='post_job_id',
        ),
        migrations.RemoveField(
            model_name='views',
            name='post_project_id',
        ),
        migrations.RemoveField(
            model_name='views',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Post_Job',
        ),
        migrations.DeleteModel(
            name='Post_Project',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Views',
        ),
    ]
