# Generated by Django 3.0.1 on 2019-12-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WW_app', '0004_auto_20191230_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('website', models.CharField(blank=True, max_length=30)),
                ('logo', models.FileField(default='images/mypic.png', upload_to='WW_app/images/')),
                ('year_est', models.IntegerField(default=2000)),
                ('employees', models.IntegerField(default=1)),
                ('ratings', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile_pic', models.FileField(default='images/mypic.png', upload_to='WW_app/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_country', models.CharField(max_length=30)),
                ('job_skills', models.CharField(max_length=150)),
                ('job_price', models.IntegerField()),
                ('job_type', models.CharField(max_length=20)),
                ('job_description', models.CharField(max_length=500)),
                ('t_likes', models.IntegerField(default=0)),
                ('t_comments', models.IntegerField(default=0)),
                ('t_views', models.IntegerField(default=0)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50)),
                ('project_country', models.CharField(max_length=30)),
                ('project_skills', models.CharField(max_length=150)),
                ('project_initial_price', models.IntegerField()),
                ('project_final_price', models.IntegerField()),
                ('project_description', models.CharField(max_length=500)),
                ('t_likes', models.IntegerField(default=0)),
                ('t_comments', models.IntegerField(default=0)),
                ('t_views', models.IntegerField(default=0)),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('otp', models.IntegerField(default=686)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verfied', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('phone', models.IntegerField()),
                ('overview', models.CharField(blank=True, max_length=300)),
                ('role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('following', models.IntegerField(blank=True, default=0)),
                ('followers', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Post_Job')),
                ('post_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Post_Project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='post_project',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.User'),
        ),
        migrations.AddField(
            model_name='post_job',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.User'),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Post_Job')),
                ('post_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Post_Project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='freelancer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.User'),
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.User'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=135)),
                ('post_job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Post_Job')),
                ('post_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Post_Project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.User')),
            ],
        ),
    ]
