# Generated by Django 3.0.1 on 2019-12-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WW_app', '0005_auto_20191230_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_Q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=90)),
                ('tags', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Freelancer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.User')),
            ],
        ),
    ]
