# Generated by Django 3.0.1 on 2019-12-31 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WW_app', '0007_forum_q_timediff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timediff', models.CharField(blank=True, max_length=30)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.User')),
                ('sf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Chat_recieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Chat_send')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.User')),
                ('rf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WW_app.Freelancer')),
            ],
        ),
    ]
