# Generated by Django 3.0.1 on 2019-12-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW_app', '0008_chat_recieve_chat_send'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='logo',
            new_name='profile_pic',
        ),
    ]
